# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: chatinside
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - '5432:5432'
    volumes:
      - ./docker/data:/var/lib/postgresql/data
